#ifndef TOUCHORD_DEFINES_H
#define TOUCHORD_DEFINES_H

#define NOTE_ON  0x90
#define NOTE_OFF 0x80
#define MIDI_CHANNEL 0
#define DEFAULT_MIDI_NOTE 60
#define MIDI_CUTOFF 74
#define MIDI_MOD 1

#define MIDI_PIN_IN_1 18
#define MIDI_PIN_IN_2 19
#define MIDI_PIN_DAT 20
#define MIDI_BAUD_RATE 31250

#define DEFAULT_CUTOFF 100

#define DEFAULT_DOUBLE_CLICK_MS 300
#define ENABLE_BOOTSEL_ON_STARTUP 0
#define ENABLE_BOOTSEL_BUTTON_CHORD 0

#define PIN_SDA  28 //14
#define PIN_SCL  29 //15
#define TRILL_ADDR 0x20
#define DISP_ADDR 0x3C

#define AUDIO_I2S_BCLK_PIN 15 //27
#define AUDIO_I2S_DATA_PIN 26 //29
#define AUDIO_I2S_LRCLK_PIN 27 //28

// BCLK is independent; the current PIO path drives DATA and LRCLK as an adjacent pair.
#define AUDIO_I2S_CLOCK_PIN_BASE AUDIO_I2S_BCLK_PIN
#define AUDIO_I2S_DMA_CHANNEL 0
#define AUDIO_I2S_PIO_INDEX   0
#define AUDIO_I2S_SM          0
#define AUDIO_I2S_LEFT_LRCLK_LEVEL 0
#define AUDIO_TEST_TONE_DEFAULT   0
#define AUDIO_TEST_TONE_FREQUENCY 440
#define AUDIO_TEST_TONE_LEVEL     5000
#define AUDIO_BOOT_TONE_BLOCKS    172

#define LED_PIN 25

#define ENCODER_A_PIN 12
#define ENCODER_B_PIN 13
#define ENCODER_TRANSITIONS_PER_STEP 1
#define ENCODER_STEP_DEBOUNCE_US 4000

#define CONTROL_0 0//1
#define CONTROL_1 8//2
#define CONTROL_2 14//3
#define NUM_CONTROLS 3 //6

#define KEY_0 7 //7
#define KEY_1 6 //8
#define KEY_2 5 //9
#define KEY_3 4 //10
#define KEY_4 3 //11
#define KEY_5 2 //12
#define KEY_6 1 //13
#define NUM_KEYS 7

#define SCALE_LEN 7
#define MAX_CHORD 6
#define CHORD_NAME_LEN 16
#define DEFAULT_OCTAVE 4
#define DEFAULT_EXTENSIONS 4
#define DEFAULT_VELOCITY 100
#define DEFAULT_INVERSION 0
#define DEFAULT_OCTAVE_COUNT 3

#define MAX_UI_DEPTH 8
#define MAX_UI_NODES 64
#define TC_SYNTH_EVENT_QUEUE_DEPTH 256
#define TC_SYNTH_VOICE_COUNT       4
#define TC_SYNTH_PATCH_NUMBER      1
#define ENABLE_INTERNAL_SYNTH_CC_PITCH 0

#endif
