#ifndef TOUCHORD_DEFINES_H
#define TOUCHORD_DEFINES_H

#define NOTE_ON  0x90
#define NOTE_OFF 0x80
#define MIDI_CHANNEL 0
#define DEFAULT_MIDI_NOTE 60
#define MIDI_CUTOFF 74
#define MIDI_MOD 1

#define MIDI_PIN_IN_1 18
#define MIDI_PIN_IN_2 19
#define MIDI_PIN_DAT 20
#define MIDI_BAUD_RATE 31250

#define DEFAULT_CUTOFF 100

#define DEFAULT_DOUBLE_CLICK_MS 300
#define ENABLE_BOOTSEL_ON_STARTUP 0
#define ENABLE_BOOTSEL_BUTTON_CHORD 0

#define PIN_SDA  14
#define PIN_SCL  15
#define TRILL_ADDR 0x20
#define DISP_ADDR 0x3C

#define AUDIO_I2S_BCLK_PIN  27
#define AUDIO_I2S_LRCLK_PIN 28
#define AUDIO_I2S_DATA_PIN  29
// The PIO program side-set drives BCLK on the base pin and LRCLK on base + 1.
#define AUDIO_I2S_CLOCK_PIN_BASE AUDIO_I2S_BCLK_PIN
#define AUDIO_I2S_DMA_CHANNEL 0
#define AUDIO_I2S_PIO_INDEX   0
#define AUDIO_I2S_SM          0
#define AUDIO_TEST_TONE_DEFAULT   0
#define AUDIO_TEST_TONE_FREQUENCY 440
#define AUDIO_TEST_TONE_LEVEL     5000
#define AUDIO_BOOT_TONE_BLOCKS    172

#define LED_PIN 25
#define CONTROL_0 1
#define CONTROL_1 2
#define CONTROL_2 3
#define CONTROL_3 4
#define CONTROL_4 5
#define CONTROL_5 6
#define NUM_CONTROLS 6
#define KEY_0 7
#define KEY_1 8
#define KEY_2 9
#define KEY_3 10
#define KEY_4 11
#define KEY_5 12
#define KEY_6 13
#define NUM_KEYS 7

#define SCALE_LEN 7
#define MAX_CHORD 6
#define CHORD_NAME_LEN 16
#define DEFAULT_OCTAVE 4
#define DEFAULT_EXTENSIONS 4
#define DEFAULT_VELOCITY 100
#define DEFAULT_INVERSION 0
#define DEFAULT_OCTAVE_COUNT 3

#define MAX_UI_DEPTH 8
#define MAX_UI_NODES 64
#define TC_SYNTH_EVENT_QUEUE_DEPTH 256
#define TC_SYNTH_VOICE_COUNT       4
#define TC_SYNTH_PATCH_NUMBER      1

#endif
